/* indent-tabs-mode: nil -*- */
/*
    yaml Qore module

    Copyright (C) 2010 - 2025 Qore Technologies, s.r.o.

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/

#include "yaml-module.h"

static void yaml_module_init(QoreModuleInitContext& ctx, ExceptionSink& xsink);
static void yaml_module_ns_init(QoreNamespace* rns, QoreNamespace* qns, ExceptionSink& xsink);
static void yaml_module_delete();

extern "C" DLLEXPORT void yaml_qore_module_desc(QoreModuleInfo& mod_info) {
    mod_info.name = "yaml";
    mod_info.version = PACKAGE_VERSION;
    mod_info.desc = "yaml module";
    mod_info.author = "David Nichols";
    mod_info.url = "http://qore.org";
    mod_info.api_major = QORE_MODULE_API_MAJOR;
    mod_info.api_minor = QORE_MODULE_API_MINOR;
    mod_info.init = yaml_module_init;
    mod_info.ns_init = yaml_module_ns_init;
    mod_info.del = yaml_module_delete;
    mod_info.license = QL_MIT;
    mod_info.license_str = "MIT";
}

QoreString NullStr("null");
QoreString SqlNullStr("sqlnull");

const char* QORE_YAML_DURATION_TAG = "!duration";
const char* QORE_YAML_NUMBER_TAG = "!number";
const char* QORE_YAML_SQLNULL_TAG = "!sqlnull";

yaml_version_directive_t yaml_ver_1_0 = {1, 0}, yaml_ver_1_1 = {1, 1}, yaml_ver_1_2 = {1, 2};

// hashdecl definitions (these are not generated by QPP)
const TypedHashDecl* hashdeclYamlSaxEvent = nullptr;
const TypedHashDecl* hashdeclYamlDocumentIteratorOptions = nullptr;
const TypedHashDecl* hashdeclYamlStreamWriterOptions = nullptr;
const TypedHashDecl* hashdeclYamlParseOptions = nullptr;

// enum definitions for use by hashdecls
QoreEnumDecl* enumYamlSaxEventType = nullptr;
QoreEnumDecl* enumYamlScalarStyle = nullptr;

// yaml event code to event string map
event_map_t event_map;

DLLLOCAL void init_yaml_functions(QoreNamespace& ns);
DLLLOCAL void init_yaml_constants(QoreNamespace& ns);
DLLLOCAL QoreEnumDecl* init_enum_YamlSaxEventType(QoreNamespace& ns);
DLLLOCAL QoreEnumDecl* init_enum_YamlScalarStyle(QoreNamespace& ns);
DLLLOCAL QoreClass* initYamlSaxParserClass(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_YamlSaxEvent(QoreNamespace& ns);
DLLLOCAL QoreClass* initYamlDocumentIteratorClass(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_YamlDocumentIteratorOptions(QoreNamespace& ns);
DLLLOCAL QoreClass* initYamlStreamWriterClass(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_YamlStreamWriterOptions(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_YamlParseOptions(QoreNamespace& ns);

const char* get_event_name(yaml_event_type_t type) {
    event_map_t::iterator i = event_map.find(type);
    return i != event_map.end() ? i->second : "unknown";
}

QoreNamespace YNS("Qore::YAML");

static void yaml_module_init(QoreModuleInitContext& ctx, ExceptionSink& xsink) {
    // add functions
    init_yaml_functions(YNS);
    // add constants
    init_yaml_constants(YNS);
    // add enums (must be before hashdecls that use them)
    enumYamlSaxEventType = init_enum_YamlSaxEventType(YNS);
    enumYamlScalarStyle = init_enum_YamlScalarStyle(YNS);
    // add hashdecls
    hashdeclYamlSaxEvent = init_hashdecl_YamlSaxEvent(YNS);
    hashdeclYamlDocumentIteratorOptions = init_hashdecl_YamlDocumentIteratorOptions(YNS);
    hashdeclYamlStreamWriterOptions = init_hashdecl_YamlStreamWriterOptions(YNS);
    hashdeclYamlParseOptions = init_hashdecl_YamlParseOptions(YNS);
    // add classes
    QC_YAMLSAXPARSER = initYamlSaxParserClass(YNS);
    YNS.addSystemClass(QC_YAMLSAXPARSER);
    QC_YAMLDOCUMENTITERATOR = initYamlDocumentIteratorClass(YNS);
    YNS.addSystemClass(QC_YAMLDOCUMENTITERATOR);
    QC_YAMLSTREAMWRITER = initYamlStreamWriterClass(YNS);
    YNS.addSystemClass(QC_YAMLSTREAMWRITER);

    // setup event map
    event_map[YAML_NO_EVENT] = "empty";
    event_map[YAML_STREAM_START_EVENT] = "stream-start";
    event_map[YAML_STREAM_END_EVENT] = "stream-end";
    event_map[YAML_DOCUMENT_START_EVENT] = "document-start";
    event_map[YAML_DOCUMENT_END_EVENT] = "document-end";
    event_map[YAML_ALIAS_EVENT] = "alias";
    event_map[YAML_SCALAR_EVENT] = "scalar";
    event_map[YAML_SEQUENCE_START_EVENT] = "sequence-start";
    event_map[YAML_SEQUENCE_END_EVENT] = "sequence-end";
    event_map[YAML_MAPPING_START_EVENT] = "mapping-start";
    event_map[YAML_MAPPING_END_EVENT] = "mapping-end";

}

static void yaml_module_ns_init(QoreNamespace* rns, QoreNamespace* qns, ExceptionSink& xsink) {
    qns->addNamespace(YNS.copy());
}

static void yaml_module_delete() {
}
